# Generated by Django 5.2.12 on 2026-03-28 05:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attendancerecord_spoof_confidence_employeephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='hours_worked',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('spoof', 'Spoof Detected'), ('unknown', 'Unknown Face')], default='checked_in', max_length=20),
        ),
    ]
